export const defaultSettings = {
  MinDistance: 20,
  MaxDistance: 30,
  RepulsionRadius: 20,
  MaxVelocity: 0.1,
  AttractionForce: 0.001,
  RepulsionForce: 500,
  AlignmentForce: 0.001,
  NodeInjectionInterval: 100,
  DrawNodes: false,
  TraceMode: false,
  InvertedColors: false,
  DebugMode: false,
  FillMode: false,
  DrawHistory: false,
  HistoryCaptureInterval: 1000,
  MaxHistorySize: 10,
  UseBrownianMotion: true,
  BrownianMotionRange: 0.01,
  ShowBounds: true,
};

export const settings = {
  ...defaultSettings,
  MinDistance: 2,
  MaxDistance: 5,
  RepulsionRadius: 8,
  MaxVelocity: 0.25,
  AttractionForce: 0.4,
  RepulsionForce: 0.7,
  AlignmentForce: 0.5,
  NodeInjectionInterval: 100,
  BrownianMotionRange: 0.01,
  DrawNodes: false,
  TraceMode: false,
  InvertedColors: false,
  DebugMode: false,
  FillMode: false,
};
